[env]
TERM = "xterm-256color"

[window]
padding = { x = 10, y = 10 }
dimensions = { columns = 100, lines = 34 }

decorations = "Buttonless"

opacity = 0.9
# blur = true


[font]
normal.family = "Cascadia Code NF"
size = 20


[cursor]
style = "Block"

